### ISSUE TITLE
[tip]

### ISSUE THREAD

**Issue by d3vaashish** [mattbierner/code2020#7]
## Required

- [x] I've searched to make sure my tip is not already covered
- [x] I believe this tip would be useful to many other VS Code users
- [x] I give Code 20/20 permission to use and share this tip for any and all purposes

## Tip

Describe your tip here. Try to explain the tip so that someone completely unfamiliar with it could understand it

https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
So, the extension enables user to preview colour inside VSCode effectively, irrespective of the format of the value used in the file say hex, RGB etc. 

It's different from default feature inside VSCode as it won't function properly for eg JSON file and the extension provides multiple choices for color-highlight.marktype  default background 

<img width="1440" alt="Screenshot 2021-10-10 at 1 49 39 PM" src="https://user-images.githubusercontent.com/25428559/136688287-7fdd9d21-fdbf-4107-bd90-79f5bac79d32.png">

**Comment by mattbierner** [comment]
Thanks! https://twitter.com/mattbierner/status/1450537239050522629
